{
 "title": "Twitch Analyzer",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Chat reader", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka processed messages rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(kafka_messages_processed_total[$__rate_interval])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Twitch messages rate  ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "rate(twitch_messages_read_total[$__rate_interval])",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  { "title": "Website", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Active clients",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    { "expr": "broadcast_hub_clients_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "Broadcast messages sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "broadcast_hub_messages_total", "legendFormat": "Total" }
   ]
  }
 ]
}